apiVersion: v1
kind: Service
metadata: 
  name: app
  labels: 
    name: app
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector: 
    name: 
    version: "1.10"
  type: LoadBalancer